name: "Setup Environment"
description: "Set up the appropriate build environment common across jobs"

inputs:
  java-version:
    description: "Java runtime version to build with"
    required: false
    default: "21"

runs:
  using: "composite"
  steps:
  - name: "gradle / validate wrapper"
    uses: "gradle/wrapper-validation-action@216d1ad2b3710bf005dc39237337b9673fd8fcd5" # v3
  - name: "java ${{ inputs.java-version }}"
    uses: "actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9" # v4
    with:
      distribution: "zulu"
      java-version: "${{ inputs.java-version }}"
  - name: "gradle / initialize"
    uses: "gradle/gradle-build-action@4c39dd82cd5e1ec7c6fa0173bb41b4b6bb3b86ff" # v3
    with:
      cache-read-only: "${{ github.ref != 'refs/heads/trunk' || github.event_name == 'pull_request' }}"
