name: "Setup Environment"
description: "Set up the appropriate build environment common across jobs"

inputs:
  java-version:
    description: "Java runtime version to build with"
    required: false
    default: "21"

runs:
  using: "composite"
  steps:
  - name: "gradle / validate wrapper"
    uses: "gradle/wrapper-validation-action@699bb18358f12c5b78b37bb0111d3a0e2276e0e2" # v2
  - name: "java ${{ inputs.java-version }}"
    uses: "actions/setup-java@9704b39bf258b59bc04b50fa2dd55e9ed76b47a8" # v4
    with:
      distribution: "zulu"
      java-version: "${{ inputs.java-version }}"
  - name: "gradle / initialize"
    uses: "gradle/gradle-build-action@29c0906b64b8fc82467890bfb7a0a7ef34bda89e" # v3
    with:
      cache-read-only: "${{ github.ref != 'refs/heads/trunk' || github.event_name == 'pull_request' }}"
