name: "Setup Environment"
description: "Set up the appropriate build environment common across jobs"

inputs:
  java-version:
    description: "Java runtime version to build with"
    required: false
    default: "21"

runs:
  using: "composite"
  steps:
  - name: "gradle / validate wrapper"
    uses: "gradle/actions/wrapper-validation@d156388eb19639ec20ade50009f3d199ce1e2808" # v4.1.0
  - name: "java ${{ inputs.java-version }}"
    uses: "actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b" # v4.5.0
    with:
      distribution: "zulu"
      java-version: "${{ inputs.java-version }}"
  - name: "gradle / initialize"
    uses: "gradle/actions/setup-gradle@d156388eb19639ec20ade50009f3d199ce1e2808" # v4.1.0
    with:
      cache-read-only: "${{ github.ref != 'refs/heads/trunk' || github.event_name == 'pull_request' }}"
