name: "Setup Environment"
description: "Set up the appropriate build environment common across jobs"

inputs:
  java-version:
    description: "Java runtime version to build with"
    required: false
    default: "21"

runs:
  using: "composite"
  steps:
  - name: "gradle / validate wrapper"
    uses: "gradle/actions/wrapper-validation@16bf8bc8fe830fa669c3c9f914d3eb147c629707" # v4.0.1
  - name: "java ${{ inputs.java-version }}"
    uses: "actions/setup-java@6a0805fcefea3d4657a47ac4c165951e33482018" # v4.2.2
    with:
      distribution: "zulu"
      java-version: "${{ inputs.java-version }}"
  - name: "gradle / initialize"
    uses: "gradle/actions/setup-gradle@16bf8bc8fe830fa669c3c9f914d3eb147c629707" # v4.0.1
    with:
      cache-read-only: "${{ github.ref != 'refs/heads/trunk' || github.event_name == 'pull_request' }}"
