name: "Setup Environment"
description: "Set up the appropriate build environment common across jobs"

inputs:
  java-version:
    description: "Java runtime version to build with"
    required: false
    default: "21"

runs:
  using: "composite"
  steps:
  - name: "gradle / validate wrapper"
    uses: "gradle/wrapper-validation-action@27152f6fa06a6b8062ef7195c795692e51fc2c81" # v2
  - name: "java ${{ inputs.java-version }}"
    uses: "actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93" # v4
    with:
      distribution: "zulu"
      java-version: "${{ inputs.java-version }}"
  - name: "gradle / initialize"
    uses: "gradle/gradle-build-action@3b1b3b9a2104c2b47fbae53f3938079c00c9bb87" # v3
    with:
      cache-read-only: "${{ github.ref != 'refs/heads/trunk' || github.event_name == 'pull_request' }}"
